//
//Copyright 2025 The Kubernetes Authors.
//
//Licensed under the Apache License, Version 2.0 (the "License");
//you may not use this file except in compliance with the License.
//You may obtain a copy of the License at
//
//http://www.apache.org/licenses/LICENSE-2.0
//
//Unless required by applicable law or agreed to in writing, software
//distributed under the License is distributed on an "AS IS" BASIS,
//WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
//See the License for the specific language governing permissions and
//limitations under the License.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v3.21.12
// source: pkg/ipcache/ipcache.proto

package ipcache

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type PodInfo struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	PodName         string                 `protobuf:"bytes,1,opt,name=pod_name,json=podName,proto3" json:"pod_name,omitempty"`
	PodNamespace    string                 `protobuf:"bytes,2,opt,name=pod_namespace,json=podNamespace,proto3" json:"pod_namespace,omitempty"`
	PodLabels       map[string]string      `protobuf:"bytes,3,rep,name=pod_labels,json=podLabels,proto3" json:"pod_labels,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	NamespaceLabels map[string]string      `protobuf:"bytes,4,rep,name=namespace_labels,json=namespaceLabels,proto3" json:"namespace_labels,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	LastUpdated     int64                  `protobuf:"varint,5,opt,name=last_updated,json=lastUpdated,proto3" json:"last_updated,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *PodInfo) Reset() {
	*x = PodInfo{}
	mi := &file_pkg_ipcache_ipcache_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PodInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PodInfo) ProtoMessage() {}

func (x *PodInfo) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_ipcache_ipcache_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PodInfo.ProtoReflect.Descriptor instead.
func (*PodInfo) Descriptor() ([]byte, []int) {
	return file_pkg_ipcache_ipcache_proto_rawDescGZIP(), []int{0}
}

func (x *PodInfo) GetPodName() string {
	if x != nil {
		return x.PodName
	}
	return ""
}

func (x *PodInfo) GetPodNamespace() string {
	if x != nil {
		return x.PodNamespace
	}
	return ""
}

func (x *PodInfo) GetPodLabels() map[string]string {
	if x != nil {
		return x.PodLabels
	}
	return nil
}

func (x *PodInfo) GetNamespaceLabels() map[string]string {
	if x != nil {
		return x.NamespaceLabels
	}
	return nil
}

func (x *PodInfo) GetLastUpdated() int64 {
	if x != nil {
		return x.LastUpdated
	}
	return 0
}

var File_pkg_ipcache_ipcache_proto protoreflect.FileDescriptor

const file_pkg_ipcache_ipcache_proto_rawDesc = "" +
	"\n" +
	"\x19pkg/ipcache/ipcache.proto\x12\aipcache\"\x80\x03\n" +
	"\aPodInfo\x12\x19\n" +
	"\bpod_name\x18\x01 \x01(\tR\apodName\x12#\n" +
	"\rpod_namespace\x18\x02 \x01(\tR\fpodNamespace\x12>\n" +
	"\n" +
	"pod_labels\x18\x03 \x03(\v2\x1f.ipcache.PodInfo.PodLabelsEntryR\tpodLabels\x12P\n" +
	"\x10namespace_labels\x18\x04 \x03(\v2%.ipcache.PodInfo.NamespaceLabelsEntryR\x0fnamespaceLabels\x12!\n" +
	"\flast_updated\x18\x05 \x01(\x03R\vlastUpdated\x1a<\n" +
	"\x0ePodLabelsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\x1aB\n" +
	"\x14NamespaceLabelsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01B\vZ\t./ipcacheb\x06proto3"

var (
	file_pkg_ipcache_ipcache_proto_rawDescOnce sync.Once
	file_pkg_ipcache_ipcache_proto_rawDescData []byte
)

func file_pkg_ipcache_ipcache_proto_rawDescGZIP() []byte {
	file_pkg_ipcache_ipcache_proto_rawDescOnce.Do(func() {
		file_pkg_ipcache_ipcache_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_pkg_ipcache_ipcache_proto_rawDesc), len(file_pkg_ipcache_ipcache_proto_rawDesc)))
	})
	return file_pkg_ipcache_ipcache_proto_rawDescData
}

var file_pkg_ipcache_ipcache_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_pkg_ipcache_ipcache_proto_goTypes = []any{
	(*PodInfo)(nil), // 0: ipcache.PodInfo
	nil,             // 1: ipcache.PodInfo.PodLabelsEntry
	nil,             // 2: ipcache.PodInfo.NamespaceLabelsEntry
}
var file_pkg_ipcache_ipcache_proto_depIdxs = []int32{
	1, // 0: ipcache.PodInfo.pod_labels:type_name -> ipcache.PodInfo.PodLabelsEntry
	2, // 1: ipcache.PodInfo.namespace_labels:type_name -> ipcache.PodInfo.NamespaceLabelsEntry
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_pkg_ipcache_ipcache_proto_init() }
func file_pkg_ipcache_ipcache_proto_init() {
	if File_pkg_ipcache_ipcache_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_pkg_ipcache_ipcache_proto_rawDesc), len(file_pkg_ipcache_ipcache_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_pkg_ipcache_ipcache_proto_goTypes,
		DependencyIndexes: file_pkg_ipcache_ipcache_proto_depIdxs,
		MessageInfos:      file_pkg_ipcache_ipcache_proto_msgTypes,
	}.Build()
	File_pkg_ipcache_ipcache_proto = out.File
	file_pkg_ipcache_ipcache_proto_goTypes = nil
	file_pkg_ipcache_ipcache_proto_depIdxs = nil
}
