FROM --platform=$BUILDPLATFORM golang:1.24 AS builder

WORKDIR /src

COPY . .
RUN go mod download

ARG TARGETOS TARGETARCH
RUN CGO_ENABLED=0 GOOS=$TARGETOS GOARCH=$TARGETARCH \
    go build -o /go/bin/kube-ip-tracker ./cmd/kube-ip-tracker

# STEP 2: Build small image
FROM gcr.io/distroless/static-debian12
COPY --from=builder --chown=root:root /go/bin/kube-ip-tracker /bin/kube-ip-tracker

CMD ["/bin/kube-ip-tracker"]
