name: Deployment to GitHub Pages

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths: 
      - 'site/**'
      - '.github/workflows/deploy-github-pages.yml'
  pull_request:
    branches:
      - main
    paths:
      - 'site/**'
      - '.github/workflows/deploy-github-pages.yml'

permissions:
  contents: write

env:
  REPO_NAME: ${{ github.event.repository.name }}
  REPO_OWNER: ${{ github.repository_owner }}

jobs:
  deploy:
    runs-on: ubuntu-latest
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v6
        with:
          fetch-depth: 0         # Fetch all history for .GitInfo and .Lastmod

      - name: Setup Hugo
        uses: peaceiris/actions-hugo@2752ce1d29631191ea3f27c23495fa06139a5b78 # v3
        with:
          hugo-version: '0.136.5'
          extended: true

      - uses: actions/setup-node@820762786026740c76f36085b0efc47a31fe5020 # v6
        with:
          node-version: '20'
          check-latest: true

      - run: |
          npm init --yes
          npm install --save-dev autoprefixer postcss-cli postcss
        working-directory: ./site

      - run: hugo --baseURL https://kube-network-policies.sigs.k8s.io --minify
        working-directory: ./site

      - name: Deploy
        uses: peaceiris/actions-gh-pages@84c30a85c19949d7eee79c4ff27748b70285e453 # v4.1.0
        if: ${{ github.ref == 'refs/heads/main' }}
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./site/public
          cname: kube-network-policies.sigs.k8s.io
